[package]
name = "cobalt-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
aovec = "1.1.0"
hashbrown = { version = "0.14.0", features = ["raw"] }
once_cell = "1.18.0"
