[package]
name = "cobalt-parser"
version = "0.5.2"
edition = "2021"

[dependencies]
cobalt-errors.path = "../cobalt-errors"
cobalt-utils.path = "../cobalt-utils"
cobalt-ast.path = "../cobalt-ast"
unicode-ident = "1.0.8"
walkdir = "2"
codespan-reporting = "0.11.1"
