[package]
name = "cobalt-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.0"
bitvec = "1.0.1"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm14-0", "internal-getters"] }
llvm-sys = { version = "140", features = ["strict-versioning"] }
unicode-ident = "1.0.5"
walkdir = "2"
toml = "0.5.9"
serde = { version = "1.0", features = ["derive"] }
semver = { version = "1.0", features = ["serde"] }
either = { version = "1.8.0", features = ["serde"] }
path-dedot = "3.0.18"
glob = "0.3.0"

[lib]
name = "cobalt"
path = "src/cobalt/lib.rs"

[[bin]]
name = "co"
path = "src/main.rs"
