[package]
name = "cobalt-lang"
version = "0.3.1"
edition = "2021"

[dependencies]
colored = "2.0.0"
bitvec = "1.0.1"
inkwell = { version = "0.1.1", features = ["llvm14-0"] }
llvm-sys = { version = "140", features = ["strict-versioning"] }
unicode-ident = "1.0.5"
walkdir = "2"
toml = "0.7.2"
serde = { version = "1.0", features = ["derive"] }
semver = { version = "1.0", features = ["serde"] }
either = { version = "1.8.0", features = ["serde"] }
glob = "0.3.0"
flate2 = "1.0.25"
git2 = "0.16.1"
zip-extract = "0.1.1"
tar = "0.4.38"
try-lazy-init = "0.0.2"
lazy_static = "1.4.0"
codespan-reporting = "0.11.1"
temp-file = "0.1.7"
ureq = "2.6.2"
path-calculate = "0.1.3"

[lib]
name = "cobalt"
path = "src/cobalt/lib.rs"

[[bin]]
name = "co"
path = "src/main.rs"
