[package]
name = "cobalt-errors"
version = "0.5.3"
edition = "2021"

[dependencies]
termcolor = "1.2.0"
miette = "5.9.0"
parking_lot = "0.12.1"
once_cell = "1.17.2"
thiserror = "1.0.40"
ordinal = "0.3.2"
