[package]
name = "cobalt-ast"
version = "0.7.0"
edition = "2021"

[dependencies]
cobalt-errors = { path = "../cobalt-errors" }
cobalt-llvm = { path = "../cobalt-llvm" }
cobalt-utils = { path = "../cobalt-utils" }
bitvec = "1.0.1"
either = "1.8.1"
glob = "0.3.1"
owned_chars = "0.3.2"
bstr = { version = "1.5.0", default-features = false, features = ["std"] }
derive_more = "0.99.17"
ref-cast = "1.0.20"
dashmap = "5.5.0"
slab = "0.4.8"
inventory = "0.3.11"
once_cell = "1.18.0"
