[package]
name = "cobalt-ast"
version = "0.5.4"
edition = "2021"

[dependencies]
cobalt-errors = { path = "../cobalt-errors" }
cobalt-utils = { path = "../cobalt-utils" }
bitvec = "1.0.1"
inkwell = { version = "0.2.0", features = ["llvm15-0"] }
llvm-sys = { version = "150" }
either = "1.8.1"
glob = "0.3.1"
owned_chars = "0.3.2"
bstr = { version = "1.5.0", default-features = false, features = ["std"] }

# features passed to llvm-sys
[features]
default = ["strict-versioning", "prefer-dynamic"]
strict-versioning = ["llvm-sys/strict-versioning"]
no-llvm-linking = ["llvm-sys/no-llvm-linking"]

prefer-dynamic = ["llvm-sys/prefer-dynamic"]
force-dynamic = ["llvm-sys/force-dynamic"]
prefer-static = ["llvm-sys/prefer-static"]
force-static = ["llvm-sys/force-static"]
