name: Build Artifacts

on:
  workflow_dispatch:
  push:
    branches:
    - auto-builds

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os:
        - runner: ubuntu-latest
          name: linux
        - runner: macos-latest
          name: apple
        llvm: [15, 16]
        link: [static, dynamic]
        profile:
        - name: debug
          profile: dev
        - name: release
          profile: release
    runs-on: "${{ matrix.os.runner }}"
    if: "${{ always() }}"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "${{ matrix.llvm }}.0"
    - name: Cache Build Outputs
      uses: actions/cache@v3
      with:
        key: test-${{ github.ref_name }}-${{ hashFiles('**/src') }}
        restore-keys: |
          test-${{ github.ref_name }}-
          test-
        path: |
          Cargo.lock
          target/
    - name: Build
      run: "cargo build --profile ${{ matrix.profile.profile }}"
    - name: Compress
      run: "gzip -fN9 'target/${{ matrix.profile.name }}/co'"
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: "co-${{ matrix.profile.name }}-${{ matrix.os.name }}-${{ matrix.link }}-${{ matrix.llvm }}.gz"
        path: "target/${{ matrix.profile.name }}/co.gz"
