name: Run Clippy, Tests, and Fmt

on:
  workflow_dispatch:
  
  push:
    branches: [main, pr-lints]
  pull_request:
    branches: [main]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Run Clippy
      run: cargo clippy --manifest-path lang/Cargo.toml --verbose -F no-llvm-linking
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "16.0"
    - name: Run Cargo Test
      run: cargo test --manifest-path lang/Cargo.toml  --verbose
  fmt:
    runs-on: ubuntu-latest
    steps:
    - name: Run Cargo Formatter
      run: cargo fmt --manifest-path lang/Cargo.toml  --verbose --check