name: Run Clippy, Tests, and Fmt

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
 CARGO_TERM_COLOR: always

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
  
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "16.0"
    - name: Cache Build Outputs
      uses: actions/cache@v3
      with:
        key: test-${{ github.ref_name }}
        path: |
          Cargo.lock
          target/
  
  clippy:
    runs-on: ubuntu-latest
    needs: [checkout, setup]
    steps:
    - name: Run Clippy
      run: cargo clippy
      env:
        RUSTFLAGS: "-Dwarnings"
  
  test:
    runs-on: ubuntu-latest
    needs: [checkout, setup]
    steps:
    - name: Run Cargo Test
      run: cargo test
  
  fmt:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
    - name: Run Cargo Formatter
      run: cargo fmt --check